repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: ''
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@2.8.7
          - '@trivago/prettier-plugin-sort-imports'
