repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: ''
    hooks:
      - id: prettier
        # additional_dependencies:
        # - prettier@2.1.2
        # - '@prettier/plugin-xml@0.12.0'

  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v6.2.0
    hooks:
      - id: cspell
